# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "zo87365.eu-central-1"
user = "jeroensmits"
password = "Welkom123!"
database = "HOL_DB"

